### ISSUE TITLE
Copyright history of xilinx_xdma_pcie_x0y0.xdc

### ISSUE THREAD

**Issue by swarren** [RHSResearchLLC/PicoEVB#11]
The file PicoEVB/Sample-Projects/Project-0/FPGA/xilinx_xdma_pcie_x0y0.xdc contains:
## (c) Copyright 2012-2012 Xilinx, Inc. All rights reserved.

I'd like to create a project for PicoEVB, and want to re-use this .xdc file. However, I can't do it with the current license. Can you please tell me where you got the original file, and which parts you added yourself as opposed to found in the original, so I can research the licensing?

Thanks.

**Comment by RHSResearchLLC** [comment]
Sorry for the extremely late response. Yes that file was autogenerated by Vivado, which it why the restrictive copyright. I was lazy and just copied their output and added PicoEVB-specific stuff.

The solution is to delete all the XDMA-specific stuff (Vivado makes its own constraint file for this anyway), and as such delete the copyright as well. When I update the project next I'll do this

**Comment by swarren** [comment]
Thanks; that's what I figured. You might find https://github.com/NVIDIA/jetson-rdma-picoevb/tree/master/fpga useful as a reference; it allows using git with Vivado without having to check in all the generated stuff.
