### ISSUE TITLE
(Sample project) Updating IPs leads to a failure in communication with the PicoEVB

### ISSUE THREAD

**Issue by CedricDly** [RHSResearchLLC/PicoEVB#13]
Hi,
I'm facing an issue when I try to compile and use the Sample Project given in the Github repository. When opening the project in Vivado 2018.3, the IP Upgrade results in a Critical Warning, telling me to look at a log file in order to fix. Here is the warning section of the log:

```
2. Customization warnings
-------------------------

Parameter 'pf1_expansion_rom_size_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to '2'
Parameter 'pf0_expansion_rom_size_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to '2'
Parameter 'pf2_expansion_rom_enabled_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'false'
Parameter 'pf1_expansion_rom_enabled_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'false'
Parameter 'pf0_expansion_rom_scale_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'Kilobytes'
Parameter 'pf2_expansion_rom_scale_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'Kilobytes'
Parameter 'pf0_expansion_rom_enabled_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'false'
Parameter 'pf3_expansion_rom_type_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'N/A'
Parameter 'pf2_expansion_rom_type_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'N/A'
Parameter 'pf1_expansion_rom_type_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'N/A'
Parameter 'pf0_expansion_rom_type_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'N/A'
Parameter 'pf1_expansion_rom_scale_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'Kilobytes'
Parameter 'pf3_expansion_rom_scale_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'Kilobytes'
Parameter 'pf3_expansion_rom_size_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to '2'
Parameter 'pf3_expansion_rom_enabled_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to 'false'
Parameter 'pf2_expansion_rom_size_mqdma' is no longer present on the upgraded IP 'project_bd_xdma_0_0', and cannot be set to '2'
```

Despite this critical warning, the bitstream is compiled but when flashed to the PicoEVB, it does not work as it should. Here is a result of the "xdma_info" command:
```
Found 1 XDMA devices
device path:    \\?\pci#ven_10ee&dev_7021&subsys_000710ee&rev_00#4&97078f1&0&00e4#{74c7e4a9-6d5d-4a70-bc0d-20691dff9e9d}
unknown Module
unknown Module
unknown Module
unknown Module
unknown Module
unknown Module
unknown Module
```

Any advice on how to solve this issue ? Should I downgrade my Vivado version ?

**Comment by jackpot51** [comment]
I would also like to know how to update the sample project successfully - I am on Vivado 2019.1.3

**Comment by Hallb3rg** [comment]
I'm also struggling with this a bit now.

The critical warning messages seem to come from a name change of a variable, and may be unrelated.

In Windows the "unknown module" is resolved after either re-installing the driver or rebooting the PC.
In case the power is cycled on the PCIe card during reboot you need to make sure you have written the bitstream to flash.
After this the xdma_info worked....almost....

Now I get data mismatch running the DMA tests ( in both Linux and windows). 
Sometimes xdma_info stops working again, and Windows crashes completely. 
I'm thinking it may be timing related since it is just some of the data that is wrong, and at different positions each run.

**Comment by Hugh3226** [comment]
I'm struggling too.
Have tried Vivado 2017.3 and 2019.1

Vivado v2017.3 (64-bit)
SW Build: 2018833 on Wed Oct 4 19:58:22 MDT 2017
IP Build: 2016188 on Wed Oct 4 21:52:56 MDT 2017

Vivado v2019.1 (64-bit)
SW Build: 2552052 on Fri May 24 14:49:42 MDT 2019
IP Build: 2548770 on Fri May 24 18:01:18 MDT 2019

**Comment by RHSResearchLLC** [comment]
I'm working on updated sample project which uses Vivado 2019, and Xilinx latest drivers (https://github.com/Xilinx/dma_ip_drivers). This sample project will also have a tool to program the flash over PCIe, which is much faster. Stay tuned

**Comment by RHSResearchLLC** [comment]
OK latest design (EVB4) fixes these problems. Issue is Xilinx "new" driver doesn't like "user" stuff at low addresses. Moved I/O addresses up to 0x1000 and higher.
