### ISSUE TITLE
Not coming out of reset on ARM (iMX6) devices

### ISSUE THREAD

**Issue by AndyCapp69** [RHSResearchLLC/PicoEVB#15]
I have tried the PicoEVB in several different types of iMX6 and the PicoEVB never comes out of reset (all LEDS on constant). I have tried modifying the PCI driver (pci-imx6.c) to extend the delays for clock stabilisation etc and even tried inverting the reset signal.  Using a scope I can see the reset line is being controlled. It does work on a Linux or Windows PC. Has anybody ever seen this working on an ARM system?

**Comment by tschaar** [comment]
I have the PicoEVB working successfully with a Jetson Xavier dev kit.

**Comment by Hugh3226** [comment]
I had the same problem.
The motherboard I use had an inverting open drain transistor on the reset line. Also a 100K pull-up and 22pF capacitor to deck.
I removed the capacitor and reduced the pull-up to 1K ohm.
We are using an iMX6.
Regards

**Comment by RHSResearchLLC** [comment]
Thanks for reporting
