### ISSUE TITLE
SPI NOR Flash "S25FL132K0XNFIQ11" obsolete?

### ISSUE THREAD

**Issue by LuckyPi** [RHSResearchLLC/PicoEVB#17]
The SPI NOR Flash "S25FL132K0XNFIQ11" included in the BOM is showing as obsolete on Mouser & Digi-Key.  Do you have a recommended alternative that will work with the sip-loader? Thanks!

**Comment by RHSResearchLLC** [comment]
I have a large cache of S25FL123K, so for the next year (at least) PicoEVB will be built with this flash. If I do change the flash part, I'll update spi-loader to support the new flash.

There are several flash parts that work with the XC7A50T part. See Xilinx UG908 appendix C.
