### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by bryankerr1986** [RHSResearchLLC/PicoEVB#7]
It would be great to know what the version numbers are for the official releases.
My PicoEVB shipped with version x"30425645", but I don't know where this version is to rebuild it...

**Comment by RHSResearchLLC** [comment]
Hello bryankerr1986,

Agreed- there should be a clear tie between the version number and the GitHub release. This is my bad. Next release I'll fix this.

The version number that gets reported is in the IOControl block; in a constant called 'deadbeef constant' :)
