### ISSUE TITLE
Vivado board files

### ISSUE THREAD

**Issue by jeremytregunna** [RHSResearchLLC/PicoEVB#8]
I've looked high and low but I can't find any board files for the PicoEVB. Is this something planned or, not?

**Comment by RHSResearchLLC** [comment]
Hi Jeremy,

Do you mean the PCB design files? If that is what you mean, I don't plan on releasing those. Besides the PCB, as designed, is a bit overkill (3 mil trace/space and via-in-pad) and expensive to manufacture.

**Comment by jeremytregunna** [comment]
@RHSResearchLLC No I didn't mean the PCB design files, I meant the vivado specific files that would describe the board to Vivado such that it would show up in a list of boards when working in the design view to set up the clocks and external I/O

**Comment by RHSResearchLLC** [comment]
@jeremytregunna Ahh OK. Sadly, I didn't know there was such a thing. That would be awesome. The closest thing I have is the [constraints file](https://github.com/RHSResearchLLC/PicoEVB/blob/master/Sample-Projects/Project-0/FPGA/constraints/xilinx_xdma_pcie_x0y0.xdc)

**Comment by jeremytregunna** [comment]
@RHSResearchLLC Yeah I found that, and that's totally workable. I just went looking for board files while working on a test design for the new board (thanks btw, it's awesome for what it is). They're definitely not required just nice integration.

**Comment by jeremytregunna** [comment]
Closing this then.
